#!/usr/bin/env bash
#
# Stage the XRoar emulator core source tree (and the CoCo ROM assets) from the
# local checkout into the Android app's generated source tree, then generate the
# Android `config.h` and register the Android UI/audio modules.
#
# XRoar uses autotools to build; Android Gradle uses CMake. Rather than run
# XRoar's configure, we stage its src/ + portalib/ into
#   app/src/main/cpp-generated/xroar/
# and let app/src/main/cpp/CMakeLists.txt compile an explicit (headless) subset
# into libcococore.so. The frontends (SDL/GTK/X11/WASM/...) are simply never
# listed, so they are not compiled. Two custom modules -- ui_android / ao_android
# (in app/src/main/cpp/xroar_android) -- provide the video output (to an
# ANativeWindow via a frame sink) and audio output (to an AudioTrack feeder).
#
# The two registration lists in src/ui.c and src/ao.c are patched (idempotent
# text transforms) to add the Android modules, guarded by __ANDROID__.
#
# Output (all git-ignored, regenerated):
#   app/src/main/cpp-generated/xroar/{src,portalib,top-config.h,config.h,.source-info}
#   app/src/main/assets-generated/xroar/roms/*.rom

set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
PROJECT_ROOT=$(cd -- "${SCRIPT_DIR}/../.." &>/dev/null && pwd)
SUPPORT_DIR="${SCRIPT_DIR}/support"
GENERATED_CORE_ROOT="${PROJECT_ROOT}/app/src/main/cpp-generated/xroar"
GENERATED_ASSET_ROOT="${PROJECT_ROOT}/app/src/main/assets-generated/xroar"

# Local checkouts (override with XROAR_SRC= / COCO_ROMS_SRC= ...).
XROAR_SRC="${XROAR_SRC:-${HOME}/Workspace/xroar-1.11}"
COCO_ROMS_SRC="${COCO_ROMS_SRC:-${HOME}/Workspace/CoCoPi-roms}"

# XRoar version label for the BuildConfig stamp.
XROAR_VERSION="1.11"

# CoCo ROMs to bundle. XRoar resolves machine/cart ROMs by basename against the
# -rompath, so these names must match the XRoar romlists:
#   coco machine  -> bas13 (Color BASIC) + extbas11 (Extended Color BASIC)
#   coco3 machine -> coco3 (Super Extended Color BASIC, 32K)
#   becker cart   -> hdbdw3bck (HDB-DOS DW3, CoCo 1/2) via @rsdos_becker
#   coco3 becker  -> hdbdw3bc3 (HDB-DOS DW3, CoCo 3 override)
COCO_ROMS=(bas13.rom extbas11.rom coco3.rom hdbdw3bck.rom hdbdw3bc3.rom)

fail() { echo "build-xroar-core.sh: $*" >&2; exit 1; }

[[ -d "${XROAR_SRC}/src" ]] || fail "XRoar source not found at ${XROAR_SRC} (set XROAR_SRC)"
[[ -f "${XROAR_SRC}/top-config.h" ]] || fail "top-config.h missing under ${XROAR_SRC}"
[[ -d "${COCO_ROMS_SRC}" ]] || fail "CoCo ROM directory not found at ${COCO_ROMS_SRC} (set COCO_ROMS_SRC)"

# --- Stage the source tree ------------------------------------------------
rm -rf "${GENERATED_CORE_ROOT}"
mkdir -p "${GENERATED_CORE_ROOT}"
rsync -a --delete \
    --exclude '.git' --exclude 'build/' --exclude '*.o' --exclude '*.a' \
    "${XROAR_SRC}/src/" "${GENERATED_CORE_ROOT}/src/"
rsync -a --delete \
    --exclude '.git' --exclude 'build/' --exclude '*.o' --exclude '*.a' \
    "${XROAR_SRC}/portalib/" "${GENERATED_CORE_ROOT}/portalib/"
cp "${XROAR_SRC}/top-config.h" "${GENERATED_CORE_ROOT}/top-config.h"

# Replace becker.c with the Android lazy-connect variant (see support/becker.c):
# upstream connects once and gives up; we need tolerance of startup ordering and
# reconnect across CoCo 2 <-> CoCo 3 machine switches.
cp "${SUPPORT_DIR}/becker.c" "${GENERATED_CORE_ROOT}/src/becker.c"

# --- Generate the Android config.h ----------------------------------------
# Headless CoCo/Dragon build: no SDL/GTK/X11/WASM/OpenGL; Becker port enabled;
# 6809/6821/6847/6883/TCC1014 parts; Dragon + CoCo3 machine archs; Dragon carts.
cat > "${GENERATED_CORE_ROOT}/config.h" <<EOF
/* Generated by tools/xroar/build-xroar-core.sh for the Android (NDK) build.
 * Headless: no SDL/GTK/X11/WASM/OpenGL. Becker port + CoCo/Dragon machines. */
#ifndef XROAR_ANDROID_CONFIG_H
#define XROAR_ANDROID_CONFIG_H

#define PACKAGE "xroar"
#define PACKAGE_NAME "XRoar"
#define PACKAGE_TARNAME "xroar"
#define PACKAGE_VERSION "${XROAR_VERSION}"
#define PACKAGE_STRING "XRoar ${XROAR_VERSION}"
#define PACKAGE_BUGREPORT "xroar@6809.org.uk"
#define PACKAGE_URL "https://www.6809.org.uk/xroar/"
#define PACKAGE_TEXT "XRoar"
#define PACKAGE_YEAR "2026"
#define VERSION "${XROAR_VERSION}"
#define RC_REV_MAJOR 1
#define RC_REV_MINOR 11

/* Standard headers (Android bionic) */
#define STDC_HEADERS 1
#define HAVE_STDIO_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define HAVE_ENDIAN_H 1
#define HAVE_REGEX_H 1

/* Library / libc features available on bionic */
#define HAVE_GETADDRINFO 1
#define HAVE_PTHREADS 1
#define HAVE_STRSEP 1
#define HAVE_STRNLEN 1
#define HAVE_POPEN 1

/* Compiler (clang) builtins / attributes */
#define HAVE___BUILTIN_EXPECT 1
#define HAVE___BUILTIN_PARITY 1
#define HAVE_FUNC_ATTRIBUTE_CONST 1
#define HAVE_FUNC_ATTRIBUTE_FORMAT 1
#define HAVE_FUNC_ATTRIBUTE_MALLOC 1
#define HAVE_FUNC_ATTRIBUTE_NONNULL 1
#define HAVE_FUNC_ATTRIBUTE_NORETURN 1
#define HAVE_FUNC_ATTRIBUTE_PURE 1
#define HAVE_FUNC_ATTRIBUTE_RETURNS_NONNULL 1
#define HAVE_VAR_ATTRIBUTE_NONSTRING 1
#define HAVE_VAR_ATTRIBUTE_PACKED 1

/* Audio: keep the null backend available as a fallback */
#define HAVE_NULL_AUDIO 1

/* Diagnostics (CPU instruction TRACE is off: it needs the *_trace.c sources). */
#define LOGGING 1

/* Sizes */
#define SIZEOF_FLOAT 4
#define SIZEOF_DOUBLE 8

/* XRoar feature selection */
#define WANT_BECKER 1
#define WANT_TRAPS 1
#define ENABLE_SNAPSHOT 1
#define WANT_MACHINE_ARCH_DRAGON 1
#define WANT_MACHINE_ARCH_COCO3 1
#define WANT_CART_ARCH_DRAGON 1
#define WANT_PART_MC6801 1
#define WANT_PART_MC6809 1
#define WANT_PART_MC6821 1
#define WANT_PART_MC6847 1
#define WANT_PART_MC6883 1
#define WANT_PART_TCC1014 1

#endif /* XROAR_ANDROID_CONFIG_H */
EOF

# --- Register the Android UI + audio modules ------------------------------
python3 - "${GENERATED_CORE_ROOT}" <<'PY'
from pathlib import Path
import sys

root = Path(sys.argv[1])

def patch(rel, transforms):
    p = root / rel
    text = p.read_text()
    for old, new in transforms:
        if new in text:
            continue  # idempotent: already applied
        if old not in text:
            sys.exit(f"build-xroar-core.sh: anchor not found in {rel}:\n{old[:160]}")
        text = text.replace(old, new, 1)
    p.write_text(text)

# src/ui.c: declare + register ui_android_module (first choice under Android).
patch("src/ui.c", [
    (
        "extern struct ui_module ui_sdl_module;\n",
        "extern struct ui_module ui_sdl_module;\n"
        "extern struct ui_module ui_android_module;\n",
    ),
    (
        "\t&ui_null_module,\n\tNULL\n};",
        "#ifdef __ANDROID__\n"
        "\t&ui_android_module,\n"
        "#endif\n"
        "\t&ui_null_module,\n\tNULL\n};",
    ),
])

# src/ao.c: declare + register ao_android_module (first choice under Android).
patch("src/ao.c", [
    (
        "extern struct module ao_null_module;\n",
        "extern struct module ao_null_module;\n"
        "extern struct module ao_android_module;\n",
    ),
    (
        "\t&ao_null_module,\n",
        "#ifdef __ANDROID__\n"
        "\t&ao_android_module,\n"
        "#endif\n"
        "\t&ao_null_module,\n",
    ),
])
PY

# --- Stage the CoCo ROM assets --------------------------------------------
rm -rf "${GENERATED_ASSET_ROOT}"
mkdir -p "${GENERATED_ASSET_ROOT}/roms"
for rom in "${COCO_ROMS[@]}"; do
    [[ -f "${COCO_ROMS_SRC}/${rom}" ]] || fail "required ROM missing: ${COCO_ROMS_SRC}/${rom}"
    cp "${COCO_ROMS_SRC}/${rom}" "${GENERATED_ASSET_ROOT}/roms/${rom}"
done

# --- Stamp -----------------------------------------------------------------
{
    printf 'source_version=%s\n' "${XROAR_VERSION}"
    printf 'source_commit=%s\n' "$(git -C "${XROAR_SRC}" rev-parse --short HEAD 2>/dev/null || echo release)"
    printf 'staged_at=%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
} > "${GENERATED_CORE_ROOT}/.source-info"

echo "XRoar core staged:"
echo "  source:  ${GENERATED_CORE_ROOT}"
echo "  roms:    ${GENERATED_ASSET_ROOT}/roms (${#COCO_ROMS[@]} files)"
